apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-dockerfile-xdn5
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-dockerfile-xdn5
    app.kubernetes.io/part-of: my-app1234567
  name: python-dockerfile-xdn5
  namespace: jkopriva-tenant
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: python-dockerfile-xdn5
    weight: 100
status: {}
